# [tool.ruff.format]
# quote-style="single"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C90"]
ignore = ["E203"]

[tool.ruff]
target-version = "py313"
line-length = 79
indent-width = 4
exclude = [".mypy_cache"]