import GameData
from PayLine import PayLine
from State import State
from Symbol import Symbol

STATE_NORMAL = State("通常")

# 図柄
SYMBOL_REDSEVEN = Symbol("赤７", "RedSeven.png")
SYMBOL_BLUESEVEN = Symbol("青７", "BlueSeven.png")
SYMBOL_BAR = Symbol("ＢＡＲ", "BAR.png")
SYMBOL_CHERRY = Symbol("チェリー", "Cherry.png")
SYMBOL_WATERMELON = Symbol("スイカ", "WaterMelon.png")
SYMBOL_BELL_A = Symbol("ベル", "Bell_A.png")
SYMBOL_REPLAY_A = Symbol("リプレイ", "Replay_A.png")

# 左リール配列
REEL_SYMBOLPATTERN_L = [
    SYMBOL_WATERMELON,
    SYMBOL_CHERRY,
    SYMBOL_REDSEVEN,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_WATERMELON,
    SYMBOL_BLUESEVEN,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_WATERMELON,
    SYMBOL_REDSEVEN,
    SYMBOL_CHERRY,
    SYMBOL_BAR,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_WATERMELON,
    SYMBOL_BLUESEVEN,
    SYMBOL_BLUESEVEN,
    SYMBOL_BLUESEVEN,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
]

# 中リール配列
REEL_SYMBOLPATTERN_C = [
    SYMBOL_CHERRY,
    SYMBOL_WATERMELON,
    SYMBOL_REDSEVEN,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
    SYMBOL_CHERRY,
    SYMBOL_WATERMELON,
    SYMBOL_CHERRY,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
    SYMBOL_CHERRY,
    SYMBOL_BLUESEVEN,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
    SYMBOL_BAR,
    SYMBOL_CHERRY,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
    SYMBOL_CHERRY,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
]

# 右リール配列
REEL_SYMBOLPATTERN_R = [
    SYMBOL_REPLAY_A,
    SYMBOL_CHERRY,
    SYMBOL_REDSEVEN,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_BAR,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_CHERRY,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_BLUESEVEN,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_CHERRY,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
]

# 有効ライン
PAYLINE_UPPER = PayLine(
    line=(
        GameData.REEL_POSITION_TOP,
        GameData.REEL_POSITION_TOP,
        GameData.REEL_POSITION_TOP,
    )
)
PAYLINE_MIDDLE = PayLine(
    line=(
        GameData.REEL_POSITION_MIDDLE,
        GameData.REEL_POSITION_MIDDLE,
        GameData.REEL_POSITION_MIDDLE,
    )
)
PAYLINE_LOWER = PayLine(
    line=(
        GameData.REEL_POSITION_BOTTOM,
        GameData.REEL_POSITION_BOTTOM,
        GameData.REEL_POSITION_BOTTOM,
    )
)
PAYLINE_RIGHTUP = PayLine(
    line=(
        GameData.REEL_POSITION_BOTTOM,
        GameData.REEL_POSITION_MIDDLE,
        GameData.REEL_POSITION_TOP,
    )
)
PAYLINE_RIGHTDOWN = PayLine(
    line=(
        GameData.REEL_POSITION_TOP,
        GameData.REEL_POSITION_MIDDLE,
        GameData.REEL_POSITION_BOTTOM,
    )
)
