from PayLine import PayLine
from State import State
from Symbol import Symbol

STATE_NORMAL = State("通常")

# 図柄
SYMBOL_REDSEVEN = Symbol("赤７", "RedSeven.png")
SYMBOL_BLUESEVEN = Symbol("青７", "BlueSeven.png")
SYMBOL_BAR = Symbol("ＢＡＲ", "BAR.png")
SYMBOL_CHERRY = Symbol("チェリー", "Cherry.png")
SYMBOL_WATERMELON = Symbol("スイカ", "WaterMelon.png")
SYMBOL_BELL_A = Symbol("ベル", "Bell_A.png")
SYMBOL_REPLAY_A = Symbol("リプレイ", "Replay_A.png")

# 左リール配列
REEL_SYMBOLPATTERN_L = [
    SYMBOL_WATERMELON,
    SYMBOL_CHERRY,
    SYMBOL_REDSEVEN,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_WATERMELON,
    SYMBOL_BLUESEVEN,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_WATERMELON,
    SYMBOL_REDSEVEN,
    SYMBOL_CHERRY,
    SYMBOL_BAR,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_WATERMELON,
    SYMBOL_BLUESEVEN,
    SYMBOL_BLUESEVEN,
    SYMBOL_BLUESEVEN,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
]

# 中リール配列
REEL_SYMBOLPATTERN_C = [
    SYMBOL_CHERRY,
    SYMBOL_WATERMELON,
    SYMBOL_REDSEVEN,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
    SYMBOL_CHERRY,
    SYMBOL_WATERMELON,
    SYMBOL_CHERRY,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
    SYMBOL_CHERRY,
    SYMBOL_BLUESEVEN,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
    SYMBOL_BAR,
    SYMBOL_CHERRY,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
    SYMBOL_CHERRY,
    SYMBOL_REPLAY_A,
    SYMBOL_BELL_A,
]

# 右リール配列
REEL_SYMBOLPATTERN_R = [
    SYMBOL_REPLAY_A,
    SYMBOL_CHERRY,
    SYMBOL_REDSEVEN,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_BAR,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_CHERRY,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_BLUESEVEN,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
    SYMBOL_REPLAY_A,
    SYMBOL_CHERRY,
    SYMBOL_WATERMELON,
    SYMBOL_BELL_A,
]

# 有効ライン
PAYLINE_UPPER = PayLine("上段", payline=(0, 0, 0))
PAYLINE_MIDDLE = PayLine("中段", payline=(1, 1, 1))
PAYLINE_LOWER = PayLine("下段", payline=(2, 2, 2))
PAYLINE_RIGHTUP = PayLine("右上がり", payline=(2, 1, 0))
PAYLINE_RIGHTDOWN = PayLine("右下がり", payline=(0, 1, 2))
